### ISSUE TITLE
/error

### ISSUE THREAD

**Issue by Blur-mons** [bneumann/vexflow-musicxml#5]
hello ,I have a error     "this.ctx.setViewBox"is not a function ,   please~      I‘m a beginner 。。。。

**Comment by bneumann** [comment]
Thx for reporting I will have a look into it today. It seems you are using the HTML canvas in which case the function is not available. You could just use a div element instead and see if that works for you.

**Comment by bneumann** [comment]
Okay this should do it. I also updated the npm registry. If you would be so kind and confirm if it works now I can close the issue

**Comment by Blur-mons** [comment]
thank u！
